CREATE TABLE `course` (
  `COURSE_ID` INT(6) NOT NULL AUTO_INCREMENT,
  `COURSE_NAME` CHAR(50) DEFAULT NULL,
  `credit` DOUBLE NOT NULL,
  PRIMARY KEY (`COURSE_ID`)
) ENGINE=INNODB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8