CREATE TABLE `user` (
  `USER_ID` int(6) NOT NULL AUTO_INCREMENT,
  `USER_NAME` char(50) DEFAULT NULL,
  `PASSWORD` char(50) DEFAULT NULL,
  `Age` int(6) NOT NULL,
  `Sex` char(50) DEFAULT NULL,
  `Race` char(50) DEFAULT 'unknown',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8